services:
  - type: web
    name: strava-tracker
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: START_DATE
        value: "2026-01-01"
      - key: END_DATE
        value: "2026-12-31"
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: "production"
      - key: MILE_TARGET
        value: 840
      - key: REDIRECT_URI
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        sync: false